services:
  blindsearch-control-room:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blindsearch-control-room
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
